### ISSUE TITLE
setAvailable: Caught error: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference

### ISSUE THREAD

**Issue by ghenry** [flutter-webrtc/callkeep#16]
```
I/flutter (22732): Caught error: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
I/flutter (22732): 	at io.wazo.callkeep.VoiceConnectionService.setAvailable(VoiceConnectionService.java:87)
I/flutter (22732): 	at io.wazo.callkeep.CallKeepModule.setAvailable(CallKeepModule.java:497)
I/flutter (22732): 	at io.wazo.callkeep.CallKeepModule.HandleMethodCall(CallKeepModule.java:188)
I/flutter (22732): 	at com.github.cloudwebrtc.flutter_callkeep.FlutterCallkeepPlugin.onMethodCall(FlutterCallkeepPlugin.java:69)
I/flutter (22732): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter (22732): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
I/flutter (22732): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
I/flutter (22732): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (22732): 	at android.os.MessageQueue.next(MessageQueue
I/flutter (22732): stackTrace: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
I/flutter (22732): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
I/flutter (22732): <asynchronous suspension>
I/flutter (22732): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
I/flutter (22732): #3      FlutterCallkeep.setAvailable (package:callkeep/src/api.dart:203:10)
```

This should be a bool not a String - https://github.com/flutter-webrtc/callkeep/blob/9c065ca0b63c69c7b399e0cecdb1a40a8caf623e/lib/src/api.dart#L197

**Comment by ghenry** [comment]
It is in the module:

https://github.com/flutter-webrtc/callkeep/blob/9c065ca0b63c69c7b399e0cecdb1a40a8caf623e/android/src/main/java/io/wazo/callkeep/VoiceConnectionService.java#L86
