### ISSUE TITLE
isCallActive: MissingPluginException(No implementation found for method isCallActive on channel FlutterCallKeep.Method

### ISSUE THREAD

**Issue by ghenry** [flutter-webrtc/callkeep#20]
Hi,

I'm timing out an inbound call notification like so

```
  Future<void> showIncomingCall(
      String ddi, String callerID, String callUUID) async {
    _logger.d('$callerID calling $ddi');
    await _cc.getForPhoneNum(callerID);
    final _callKeep = Get.find<CallController>().callKeep;

    Get.find<FirebaseAnalyticsService>()
        .analytics
        .logEvent(name: 'IncomingCallEvent');

    _callKeep.displayIncomingCall(callUUID, callerID,
        handleType: 'number',
        localizedCallerName:
            _cc.contacts.isEmpty ? ddi : _cc.contacts[0].toString(),
        hasVideo: false);

    Timer(const Duration(seconds: INCOMING_CALL_TIMEOUT_SECS), () async {
      if (await _callKeep.isCallActive(callUUID) == false) {
        _logger.d('Incoming call timed out.');
        Get.find<FirebaseAnalyticsService>()
            .analytics
            .logEvent(name: 'IncomingCallTimeoutEvent');
        _callKeep.rejectCall(callUUID);
      }
    });
  }
```

```
E/flutter (26386): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method isCallActive on channel FlutterCallKeep.Method)
E/flutter (26386): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (26386): <asynchronous suspension>
E/flutter (26386): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (26386): #2      FlutterCallkeep.isCallActive (package:callkeep/src/api.dart:157:8)
E/flutter (26386): #3      NotificationsController.showIncomingCall.<anonymous closure> (package:SureVoIPTalk/src/controller/notifications.dart:69:27)
E/flutter (26386): #4      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (26386): #5      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (26386): #6      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (26386): #7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (26386): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (26386): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (26386): #10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (26386): #11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (26386): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (26386): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (26386): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by ghenry** [comment]
Ah, iOS only. How can I tell if a call was answered before I timeout then....

**Comment by ghenry** [comment]
I'll do this on the SIP side. Closing.
